version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: /root/  
    steps:
      - run: apt update && apt install -y bash && apt install -y curl
      - slack/notify: 
          channel: Advait Kukade
          color: '#42e2f4' 
          mentions: 'advaitkukade@gmail.com' 
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
      - run: curl -k -X POST -H https://hooks.slack.com/services/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
      
