version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: /root/
    steps:
      - run: apt update && apt install -y bash && apt install -y curl
      - slack/status:
       #   fail_only: true
       #  mentions: 'advaitkukade@gmail.com' 
       #   message: 'Pending Approval.'
          only_for_branches: master 
          webhooks: |
            https://hooks.slack.com/services/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
            
#orbs:
#  slack: circleci/slack@1.0.0
