version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk update && apk add bash && apk add curl
      - slack/notify:
          color: '#42e2f4' 
          mentions: 'advaitkukade@gmail.com' 
          message: This is a custom message notification.
          webhook: https://hooks.slack.com/services/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
