version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk update && apk add bash && apk add curl
      - slack/notify:
          channel: circleci
          color: '#42e2f4' 
          mentions: 'advaitkukade@gmail.com' 
          message: This is a custom message notification.
          webhook: https://hooks.slack.com/services/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
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
