version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk update & apk add bash 
      - slack/status:
          fail_only: true 
          mentions: 'advaitkukade@gmail.com' 
          only_for_branches: master
          webhook: https://hooks.slack.com/services/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
